# Generated by Django 4.1.4 on 2023-12-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordserver',
            name='permissions',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
