# Generated by Django 4.1.4 on 2023-12-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_discordserver_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discordserver',
            options={'ordering': ['server_id']},
        ),
        migrations.RenameField(
            model_name='discordserver',
            old_name='name',
            new_name='auth_code',
        ),
    ]
