# Generated by Django 4.1.4 on 2023-12-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_discordserver_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discordserver',
            unique_together={('server_id', 'auth_code')},
        ),
        migrations.RemoveField(
            model_name='discordserver',
            name='permissions',
        ),
    ]
