# Generated by Django 4.1.4 on 2023-12-16 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_discordserver_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discordserver',
            unique_together=set(),
        ),
    ]
